"""add table occupation and places_occupees

Revision ID: 2a263642996d
Revises: 
Create Date: 2026-06-23 16:32:39.184657

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2a263642996d'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # op.create_foreign_key(None, 'commande_items', 'commandes', ['commande_id'], ['id'])
    # op.create_foreign_key(None, 'commande_items', 'produits', ['produit_id'], ['id'])
    op.add_column('commandes', sa.Column('occupation_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'commandes', 'table_occupations', ['occupation_id'], ['id'])
    # op.create_foreign_key(None, 'commandes', 'tables', ['table_id'], ['id'])
    op.add_column('table_occupations', sa.Column('ended_at', sa.DateTime(), nullable=True))
    op.add_column('tables', sa.Column('places_occupees', sa.Integer(), nullable=True))
    # op.alter_column(
    #     'tables', 'code_acces',
    #            existing_type=sa.VARCHAR(length=255),
    #            type_=sa.String(length=50),
    #            existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tables', 'code_acces',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
    op.drop_column('tables', 'places_occupees')
    op.drop_column('table_occupations', 'ended_at')
    op.drop_constraint(None, 'commandes', type_='foreignkey')
    op.drop_constraint(None, 'commandes', type_='foreignkey')
    op.drop_column('commandes', 'occupation_id')
    op.drop_constraint(None, 'commande_items', type_='foreignkey')
    op.drop_constraint(None, 'commande_items', type_='foreignkey')
    # ### end Alembic commands ###
