"""remove access token

Revision ID: 398bde4bdf8a
Revises: 2a263642996d
Create Date: 2026-07-23 17:13:08.182168

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '398bde4bdf8a'
down_revision: Union[str, Sequence[str], None] = '2a263642996d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_restaurant_history_restaurant_id'), table_name='user_restaurant_history')
    op.drop_index(op.f('ix_user_restaurant_history_user_id'), table_name='user_restaurant_history')
    op.drop_table('user_restaurant_history')
    op.create_foreign_key(None, 'commande_items', 'produits', ['produit_id'], ['id'])
    op.create_foreign_key(None, 'commande_items', 'commandes', ['commande_id'], ['id'])
    op.create_foreign_key(None, 'commandes', 'tables', ['table_id'], ['id'])
    op.alter_column('tables', 'code_acces',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=50),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tables', 'code_acces',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
    op.drop_constraint(None, 'commandes', type_='foreignkey')
    op.drop_constraint(None, 'commande_items', type_='foreignkey')
    op.drop_constraint(None, 'commande_items', type_='foreignkey')
    op.create_table('user_restaurant_history',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('restaurant_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('joined_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('left_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['restaurant_id'], ['restaurants.id'], name=op.f('user_restaurant_history_restaurant_id_fkey')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('user_restaurant_history_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('user_restaurant_history_pkey'))
    )
    op.create_index(op.f('ix_user_restaurant_history_user_id'), 'user_restaurant_history', ['user_id'], unique=False)
    op.create_index(op.f('ix_user_restaurant_history_restaurant_id'), 'user_restaurant_history', ['restaurant_id'], unique=False)
    # ### end Alembic commands ###
